@startuml
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state SISTEMA_DISPONIBLE

state "iniciarAutomatizacion()" as MainBlock {
    
    [*] --> Paso1
    note on link
        ' Verbo estricto del ACTOR: SOLICITA
        **Usuario solicita** iniciar la automatización
    end note

    state Paso1 as " "
    
    Paso1 --> Paso2
    note on link
        ' Verbo estricto del SISTEMA: PERMITE SOLICITAR
        ' (Se usa cuando el sistema valida ok y deja pasar)
        **Sistema permite solicitar** el inicio de la configuración
    end note

    state Paso2 as " "

    Paso2 --> [*]
    note on link
        ' Verbo estricto del SISTEMA: MUESTRA / VISUALIZA
        **Sistema muestra** el monitoreo en segundo plano
    end note
}

SISTEMA_DISPONIBLE -down-> MainBlock

state AUTOMATIZACION_ACTIVA
MainBlock -down-> AUTOMATIZACION_ACTIVA

@enduml