@startuml eliminarTarea
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #008000
}
skinparam note {
    BackgroundColor #FEFECE
    BorderColor #D7B75F
}

state TAREA_ABIERTO

state "eliminarTarea()" as eliminarTarea {
    state " " as Inicio <<start>>
    state " " as Confirmacion
    state " " as Confirmacion2
    state " " as Estado2
    state " " as Fin <<end>>
    
    Inicio --> Confirmacion
    note on link
        <b>Usuario</b> solicita eliminar tarea
    end note

        Confirmacion --> Confirmacion2
    note on link
                <b>Sistema</b> solicita confirmación
    end note
    
    Confirmacion2 --> Estado2
    note on link
                <b>Usuario</b> introduce confirmación
    end note

    Estado2 --> Fin
    note on link
        <b>Sistema</b> presenta listado actualizado
    end note
}

state TAREAS_ABIERTO

TAREA_ABIERTO --> eliminarTarea
eliminarTarea --> TAREAS_ABIERTO
note on link
    Tarea eliminada
end note
@enduml