@startuml eliminarGrupo
skinparam monochrome false
skinparam shadow false
top to bottom direction

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #009900
}

skinparam note {
    BackgroundColor #FFFFE0
    BorderColor #B0B060
}

state "GRUPOS_ABIERTO" as Inicio

state "eliminarGrupo()" as EliminarGrupoContainer {
    state " " as Paso1
    state " " as Paso2
    state " " as Paso3

    [*] --> Paso1
    note on link
        **Administrador** solicita eliminar grupo
    end note

    Paso1 --> Paso2
    note on link
        **Sistema** presenta solicitud de confirmación
        • **Sistema** permite solicitar confirmar eliminación
        • **Sistema** permite solicitar cancelar eliminación
    end note

    Paso2 --> Paso3
    note on link
        **Administrador** solicita confirmar eliminación
    end note

    Paso3 --> [*]
    note on link
        **Sistema** presenta lista de grupos actualizada
    end note
}

state "GRUPOS_ABIERTO" as Fin

Inicio --> EliminarGrupoContainer
EliminarGrupoContainer --> Fin
EliminarGrupoContainer -[#red]right-> Fin : cancelar eliminación
@enduml