@startuml eliminarGrupo
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

' Estado inicial arriba
state GRUPOS_ABIERTO

state "eliminarGrupo()" as MainBlock {
    [*] --> Paso1
    note on link
        **Administrador** solicita eliminar grupo
    end note

    state Paso1 as " "
    Paso1 --> Paso2
    note on link
        **Sistema** solicita confirmación de eliminación
    end note

    state Paso2 as " "
    Paso2 --> Paso3
    note on link
        **Administrador** introduce la confirmación
    end note

    state Paso3 as " "
    Paso3 --> [*]
    note on link
        **Sistema** elimina el grupo 
        y actualiza la lista
    end note
}

' Creamos un "alias" para que aparezca una copia abajo
state "GRUPOS_ABIERTO" as GRUPOS_ABIERTO_FINAL

GRUPOS_ABIERTO -down-> MainBlock
MainBlock -down-> GRUPOS_ABIERTO_FINAL
@enduml