@startuml marcarCompletada
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #008000
}
skinparam note {
    BackgroundColor #FEFECE
    BorderColor #D7B75F
}

state TAREAS_ABIERTO
state "TAREAS_ABIERTO" as TAREAS_ABIERTO_FINAL

state "marcarCompletada()" as marcarCompletada {
    state " " as Inicio <<start>>
    state " " as Intermedio
    state " " as Fin <<end>>
    
    Inicio --> Intermedio
    note on link
        <b>Usuario</b> solicita marcar completada
    end note
    
    Intermedio --> Fin
    note on link
        <b>Sistema</b> visualiza estado completado
        * Fecha finalización
    end note
}

TAREAS_ABIERTO --> marcarCompletada
marcarCompletada --> TAREAS_ABIERTO_FINAL
@enduml