@startuml DiagramaPlanificaciónYDetalles
left to right direction
actor "Administrador" as Admin


package "Planificación y Detalles" {
    usecase "establecerHorario()" as UC_D1
    usecase "definirLocalizacion()" as UC_D2
    usecase "configurarRecordatorio()" as UC_D3
    usecase "asignarTareaAUsuario()" as UC_D4
    
}

Admin --> UC_D1
Admin --> UC_D2
Admin --> UC_D3
Admin --> UC_D4

@enduml