@startuml DiagramaPlanificaciónYDetalles
actor "Administrador" as Admin
actor "Miembro" as Miem

    package "Planificación y Detalles" {
        usecase "Establecer Horarios" as UC_D1
        usecase "Definir Localización" as UC_D2
        usecase "Configurar Recordatorio" as UC_D3
        usecase "Vincular Tareas (Dependencias)" as UC_D4
    }

    Admin --> UC_D1
    Admin --> UC_D2
    Admin --> UC_D3
    Miem --> UC_D3
    Admin --> UC_D4
@enduml