@startuml abrirEdicionGrupo
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state GRUPO_ABIERTO
state CONSULTA_TAREAS_ABIERTO
state ORGANIZACION_GRUPOS_ABIERTO

state "abrirEdicionGrupo()" as MainBlock {

    [*] --> Paso1
    note on link
        **Administrador** selecciona 'Volver'
    end note

    state Paso1 as " "

    Paso1 --> Paso2
    note on link
        **Sistema** guarda cambios y recupera la lista de grupos
    end note

    state Paso2 as "Cierre y Recuperación"

    Paso2 --> [*]
    note on link
        **Sistema** muestra el listado de grupos
    end note
}

GRUPO_ABIERTO -down-> MainBlock
CONSULTA_TAREAS_ABIERTO -left-> MainBlock

MainBlock -down-> ORGANIZACION_GRUPOS_ABIERTO
note on link
    Retorno a la gestión de grupos
end note

@enduml