@startuml volverAInicio
top to bottom direction
skinparam classAttributeIconSize 0
skinparam ArrowColor Green

state "AUTOMATIZACION_ACTIVA" as AUTOMATIZACION_ACTIVA
state "SISTEMA_DISPONIBLE" as SISTEMA_DISPONIBLE

state "volverAInicio()" as UC {
 
  [*] --> N1

  state " " as N1
  state " " as N2

  N1 --> N2
  note on link
  Usuario solicita parar la automatizacion y volver a inicio
  end note

  N2 --> [*]
  note on link
  Sistema muestra inicio 
  end note
}

AUTOMATIZACION_ACTIVA --> UC : volverAInicio()
UC --> SISTEMA_DISPONIBLE : volverAInicio()

@enduml
