@startuml DiagramaOrganizaciónYGrupos
left to right direction
actor "Administrador" as Admin


package "Organización y Grupos" {
    usecase "crearGrupo()" as UC_G1
    usecase "invitarUsuario()" as UC_G2
    usecase "editarGrupo()" as UC_G3
    usecase "eliminarGrupo()" as UC_G4
    usecase "editarMiembro()" as UC_G5
    usecase "abrirGrupos()" as UC_G6

}

Admin --> UC_G1
Admin --> UC_G2
Admin --> UC_G3
Admin --> UC_G4
Admin --> UC_G5
Admin --> UC_G6

@enduml