@startsalt
{+
  ^""Nueva / Editar Tarea""^
  .
  {
    Titulo de la Tarea: | "Introduzca el título...          "
    Descripción:        | "Detalles de la tarea...          "
    Fecha Vencimiento:  | "DD/MM/AAAA                       "
    Prioridad:          | ^Media^
    Asignar a:          | ^Seleccionar Usuario^
  }
  .
  {/ 
   [Cancelar] | [Guardar Tarea]
  }
}
@endsalt