@startuml asignarTareaAUsuario
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state GRUPO_ABIERTO

state "asignarTareaAUsuario()" as MainBlock {

    [*] --> Paso1
    note on link
        **Administrador** selecciona 'Asignar Tarea'
        y selecciona Tarea y Usuario
    end note

    state Paso1 as "Selección Tarea y Usuario"

    Paso1 --> Paso2
    note on link
        **Sistema** valida la existencia y disponibilidad
        de la Tarea y del Usuario
    end note

    state Paso2 as "Validación de Tarea/Usuario"

    Paso2 --> Exito
    note on link
        [Tarea y Usuario válidos]
    end note

    Paso2 --> Fracaso
    note on link
        [Tarea o Usuario no válido O Tarea ya asignada]
    end note

    state Exito as " "
    note right
        **Sistema** registra la asignación y notifica al usuario
    end note

    state Fracaso as " "
    note right
        **Sistema** muestra mensaje de error
    end note

    Exito --> [*]
    Fracaso --> [*]
    note on link
        **Sistema** actualiza la vista de asignaciones
    end note
}

GRUPO_ABIERTO -down-> MainBlock

MainBlock -down-> GRUPO_ABIERTO

state otras as "editarGrupo()\ninvitarUsuario()"
GRUPO_ABIERTO -left-> otras
otras -right-> GRUPO_ABIERTO

state cerrar as "abrirEdicionGrupo()"
state ORGANIZACION_GRUPOS_ABIERTO
GRUPO_ABIERTO -right-> cerrar
cerrar -down-> ORGANIZACION_GRUPOS_ABIERTO

@enduml