actor "Sistema" as S
actor "Administrador" as Admin

    package "Automatización" {
        usecase "Detectar Conflicto de Horario" as UC_A1
        usecase "Notificar Conflicto" as UC_A2
        usecase "Enviar Recordatorio" as UC_A3
        usecase "Verificar Hora Actual" as UC_A4
    }

    S --> UC_A4
    UC_A4 ..> UC_A1 : <<include>>
    UC_A1 ..> UC_A2 : <<extend>>
    UC_A4 ..> UC_A3 : <<extend>>
    
    UC_A2 --> Admin : "Alerta al Administrador"
    UC_A3 --> Admin : "Avisa al Administrador"