@startuml cerrarSesion
top to bottom direction
skinparam classAttributeIconSize 0
skinparam ArrowColor Green

state "SISTEMA_DISPONIBLE" as SISTEMA_DISPONIBLE
state "SESION_CERRADA" as SESION_CERRADA

state "cerrarSesion()" as UC {
 
  [*] --> N1

  state " " as N1
  state " " as N2

  N1 --> N2
  note on link
  Usuario solicita cerrar sesion
  end note

  N2 --> [*]
  note on link
  Sistema permite solicitar:
  • confirmar cierre
  • cancelar cierre
  end note
}

SISTEMA_DISPONIBLE --> UC : cerrarSesion()
UC --> SESION_CERRADA : confirmar
UC --> SISTEMA_DISPONIBLE : cancelar

@enduml
