@startuml cerrarSesion
top to bottom direction
skinparam classAttributeIconSize 0
skinparam ArrowColor Green

state "SISTEMA_DISPONIBLE" as SISTEMA_DISPONIBLE
state "SESION_CERRADA" as SESION_CERRADA

state "cerrarSesion()" as cerrarSesion {
  [*] --> paso

  note right #FFF2CC
  Usuario solicita cerrar sesion
  end note 

  paso --> fin

  note right #FFF2CC
  Sistema solicita confirmacion de cierre
  • Permite confirmar
  • Permite cancelar
  • Si confirma, limpia sesion y vuelve a inicio
  end note

  fin --> [*]
}

SISTEMA_DISPONIBLE --> cerrarSesion : cerrarSesion()
cerrarSesion --> SESION_CERRADA : (confirmar)
cerrarSesion --> SISTEMA_DISPONIBLE : (cancelar)

@enduml
