@startuml invitarUsuario
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state GRUPO_ABIERTO

state "invitarUsuario()" as MainBlock {

    [*] --> Paso1
    note on link
        **Administrador** solicita invitar usuario
    end note

    state Paso1 as " "

    Paso1 --> Paso2
    note on link
        **Sistema** permite introducir el identificador
    end note

    state Paso2 as " "

    Paso2 --> Paso3
    note on link
        **Administrador** introduce el identificador
    end note

    state Paso3 as " "

    Paso3 --> [*]
    note on link
        **Sistema** visualiza la confirmación del envío
    end note
}

state "GRUPO_ABIERTO" as GRUPO_ABIERTO_FINAL

GRUPO_ABIERTO -down-> MainBlock
MainBlock -down-> GRUPO_ABIERTO_FINAL

@enduml