@startuml invitarUsuario
skinparam monochrome false
skinparam shadow false
top to bottom direction

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #009900
    StartColor Black
    EndColor Black
}

skinparam note {
    BackgroundColor #FFFFE0
    BorderColor #B0B060
    FontName Arial
}

state "GRUPO_ABIERTO" as Inicio

state "invitarUsuario()" as MainBlock {
    
    state " " as Paso1
    state " " as Paso2
    state " " as Paso3

    [*] --> Paso1
    note on link
        **Administrador** solicita invitar usuario
    end note

    Paso1 --> Paso2
    note on link
        **Sistema** presenta formulario de invitación
        • **Sistema** permite introducir el identificador
        • **Sistema** permite solicitar enviar invitación
        • **Sistema** permite solicitar cancelar invitación
    end note

    Paso2 --> Paso3
    note on link
        **Administrador** introduce el identificador y solicita enviar
    end note

    Paso3 --> [*]
    note on link
        **Sistema** visualiza la confirmación del envío
    end note
}

state "GRUPO_ABIERTO" as Fin

Inicio --> MainBlock

MainBlock --> Fin

MainBlock -[#red]right-> Fin
note on link
    cancelar invitación
end note

@enduml