@startuml DiagramaContextoMiembro
left to right direction
skinparam linetype polyline

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "TAREAS_ABIERTO" as ListProgramas

[*] --> NoAuth

NoAuth --> Menu : iniciarSesion()

Menu --> NoAuth : cerrarSesion()
Menu --> ListProgramas: abrirTareas()

ListProgramas --> ListProgramas: marcarCompletada()

ListProgramas --> Menu: completarGestion()
@enduml