@startuml unirseAGrupo
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state GRUPOS_ABIERTO

state "agruparUsuario()" as MainBlock {
    
    [*] --> Paso1
    note on link
        **Administrador** solicita agrupar a un usuario 
    end note

    state Paso1 as " "
    
    Paso1 --> Paso2
    note on link
        **Sistema** permite introducir los datos del usuario y grupo
    end note

    state Paso2 as " "

    Paso2 --> Paso3
    note on link
        **Administrador** introduce la asignación del usuario al grupo
    end note

    state Paso3 as " "

    Paso3 --> [*]
    note on link
        **Sistema** visualiza la actualización de los grupos
    end note
}

state "GRUPOS_ABIERTO" as GRUPOS_ABIERTO_FINAL

GRUPOS_ABIERTO -down-> MainBlock
MainBlock -down-> GRUPOS_ABIERTO_FINAL

@enduml