@startuml crearTarea
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #008000
}
skinparam note {
    BackgroundColor #FEFECE
    BorderColor #D7B75F
}

state TAREAS_ABIERTO

state "crearTarea()" as crearTarea {
    state " " as Inicio <<start>>
    state " " as Formulario
    state " " as Procesando
    state " " as Fin <<end>>
    
    Inicio --> Formulario
    note on link
        <b>Usuario</b> solicita introducir tarea
    end note
    
    Formulario --> Procesando
    note on link
        <b>Sistema</b> permite introducir datos
        * Título, Fecha, Asignado
    end note

    Procesando --> Fin
    note on link
        <b>Usuario</b> introduce datos
        <b>Sistema</b> visualiza nueva tarea
    end note
}

TAREAS_ABIERTO --> crearTarea
crearTarea --> TAREAS_ABIERTO
@enduml