@startuml
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor Green
}
skinparam note {
    BackgroundColor LightYellow
    BorderColor Gray
}

state CONFLICTO_ABIERTO

state "resolverConflicto()" as MainBlock {
    
    [*] --> Paso1
    note on link
        **Usuario** revisa los detalles del conflicto
        Selecciona una acción correctiva
    end note

    state Paso1 as " "
    
    Paso1 --> Paso2
    note on link
        **Sistema** aplica los cambios de horario
    end note

    state Paso2 as " "

    Paso2 --> [*]
    note on link
        **Sistema** marca el conflicto como resuelto
        Retoma el monitoreo
    end note
}

CONFLICTO_ABIERTO -down-> MainBlock

state AUTOMATIZACION_ACTIVA
MainBlock -down-> AUTOMATIZACION_ACTIVA



@enduml