@startuml abrirTareas
skinparam state {
    BackgroundColor White
    BorderColor Black
    ArrowColor #008000
}
skinparam note {
    BackgroundColor #FEFECE
    BorderColor #D7B75F
}

state GRUPO_ABIERTO
state SISTEMA_DISPONIBLE
state TAREA_ABIERTO

state "abrirTareas()" as abrirTareas {
    state " " as Inicio <<start>>
    state " " as Intermedio
    state " " as Fin <<end>>
    
    Inicio --> Intermedio
    note on link
        <b>Usuario</b> solicita abrir tareas
    end note
    
    Intermedio --> Fin
    note on link
        <b>Sistema</b> muestra lista de tareas
        * Tareas pendientes
        * Tareas completadas
    end note
}

state TAREAS_ABIERTO


GRUPO_ABIERTO --> abrirTareas
SISTEMA_DISPONIBLE--> abrirTareas
TAREA_ABIERTO --> abrirTareas
abrirTareas --> TAREAS_ABIERTO
note on link
    Lista de tareas disponible para edición
end note
@enduml