@startuml configurarRecordatorio

hide empty description
skinparam linetype polyline

state in1 as "PLANIFICACION_ABIERTO"
in1 -[#green]-> configurarRecordatorio

state configurarRecordatorio as "configurarRecordatorio()" {

    state DefiniendoRecordatorio as " "
    state ConfirmandoRecordatorio as " "

    [*] -[#green]-> DefiniendoRecordatorio
    note on link
        <b>Usuario</b> introduce tipo y tiempo de recordatorio
    end note

    DefiniendoRecordatorio -[#green]-> ConfirmandoRecordatorio
    note on link
        <b>Sistema</b> muestra resumen del recordatorio
    end note

    ConfirmandoRecordatorio -[#green]-> [*]
    note on link
        <b>Sistema</b> guarda recordatorio
    end note
}

configurarRecordatorio -[#green]-> PLANIFICACION_ABIERTO
note on link
    Recordatorio creado
end note

@enduml
