@startuml completarGestion
top to bottom direction
skinparam classAttributeIconSize 0
skinparam ArrowColor Green

state "GESTION_ABIERTA" as GESTION_ABIERTA
state "SISTEMA_DISPONIBLE" as SISTEMA_DISPONIBLE

state "completarGestion()" as UC {

  [*] --> N1

  state " " as N1
  state " " as N2 

  N1 --> N2
  note on link
  Usuario solicita completar gestion
  end note

  N2 --> [*]
  note on link
  Sistema permite solicitar:
  • guardar
  • descartar
  • cancelar
  end note
}

GESTION_ABIERTA --> UC : completarGestion()
UC --> SISTEMA_DISPONIBLE : guardar
UC --> SISTEMA_DISPONIBLE : descartar
UC --> GESTION_ABIERTA : cancelar

@enduml
