@startuml vincularTareas

skinparam linetype polyline

state in1 as "PLANIFICACION_ABIERTO"
in1 -[#green]-> vincularTareas

state vincularTareas as "vincularTareas()" {

    state " " as MostrandoTareas
    state " " as SeleccionandoTareas

    [*] -[#green]-> MostrandoTareas
    note on link
    <b>Sistema</b> muestra tareas disponibles
    end note

    MostrandoTareas -[#green]-> SeleccionandoTareas
    note on link
    <b>Usuario</b> selecciona tareas
    end note

    SeleccionandoTareas -[#green]-> [*]
    note on link
    <b>Sistema</b> vincula tareas a la planificación
    end note
}

vincularTareas -[#green]-> PLANIFICACION_ABIERTO
note on link
Tareas vinculadas correctamente
end note

@enduml
